# Generated by Django 6.0.6 on 2026-06-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmenttask_project_employee_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='exam_type',
            field=models.CharField(blank=True, default='', help_text='comprehensive, bigfive, pdp, mbti', max_length=30, verbose_name='考试类型'),
        ),
        migrations.AlterField(
            model_name='assessmenttask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
