# Generated by Django 6.0.6 on 2026-06-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='超管可不关联', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch', verbose_name='所属分公司'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('hr_admin', '分公司管理员'), ('project_admin', '项目管理员')], default='hr_admin', max_length=20, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('code', models.CharField(help_text='如 SZ-HR、GZ-TECH 等', max_length=20, unique=True, verbose_name='项目代码')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.branch', verbose_name='所属分公司')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['branch__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ForeignKey(blank=True, help_text='项目管理员关联，超管/分公司管理员可不填', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.project', verbose_name='所属项目'),
        ),
    ]
